routes/web.php
<?php

use App\Http\Controllers\StudentController;
use App\Models\Student;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', [StudentController::class,'index']);
Route::get('/student/create', [StudentController::class,'create'])->name('create_students');*/



Route::resource('students', StudentController::class);

app/Models/Student.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Student extends Model
{

    use HasFactory;
    protected $guarded = [];
}

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/StudentController.php
<?php

namespace App\Http\Controllers;

use App\Models\Student;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class StudentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Application|Factory|View
     */
    public function index()
    {
        return view('students.index',['students' => Student::all()]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Application|Factory|View
     */
    public function create()
    {
        return view('students.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(Request $request)
    {

        $validated = $request->validate([
            'matricule' => 'required|max:15',
            'first_name' => 'required|max:15',
            'last_name' => 'required|max:15',
            'email' => 'required|email',
            'phone' => 'required|max:15',
        ]/*,
            [
                'matricule.required' => 'Le Matricule est obligatoire !',
                'first_name.required' => 'Veuillez renseigner un prénom svp',
                'last_name.required' => 'Le Nom est obligatoire',
                'email.required' => 'L\'Email est obligatoire',
                'email.email' => 'Veuillez renseigner un email valide',
                'phone.required' => 'Telephone obligatoire',

            ]*/);
      /*  return $validated;*/
      /*  Student::create([
              'matricule' => $request->get('matricule'),
              'first_name' => $request->get('prenom'),
              'last_name' => $request->get('nom'),
              'email' => $request->get('email'),
              'phone' => $request->get('tel')
          ]);*/

        return redirect()->back()->with('success','Student created successfully');
        // return response()->json(['message' => "Student created successfully"]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return Application|Factory|View
     */
    public function show($id)
    {
        $student = Student::find($id);

        return view('students.show',compact('student'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id)
    {
        $student = Student::find($id);
        return view('students.edit',compact('student'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
        return $request->all();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function destroy($id)
    {
        $student = Student::find($id);
        $student->delete();

        return response()->json(['m essage' => "Student deleted successfully"]);
    }
}

resources/views/students/create.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
</head>
<body>

<div class="card col-sm-6 m-auto mt-5">
    <div class="card-body">
        <h1 class="justify-content-center">Nouveau Etudiant</h1>
      {{--  @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif--}}
        <form method="post" action="{{route('students.store')}}">
            @csrf
            <fieldset>
                <div class="mb-3">
                    <label for="Inputmatricule" class="form-label">Matricule</label>
                    <input type="text" id="Inputmatricule" class="form-control"
                           placeholder="Votre matricule" name="matricule">
                    @error('matricule')
                    <div class="alert alert-danger">{{ $message }}</div>
                    @enderror

                </div>
                <div class="mb-3">
                    <label for="InputFirstname" class="form-label">Prénom</label>
                    <input type="text" id="InputFirstname" class="form-control" placeholder="Votre prénom" name="prenom">
                    @error('first_name')
                    <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                </div>
                <div class="mb-3">
                    <label for="InputLastname" class="form-label">Nom</label>
                    <input type="text" id="InputLastname" class="form-control" placeholder="Votre nom" name="nom">
                    @error('last_name')
                    <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                </div>
                <div class="mb-3">
                    <label for="InputEmail" class="form-label">Email</label>
                    <input type="text" id="InputEmail" class="form-control" placeholder="exemple@gmail.com" name="email">
                    @error('email')
                    <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                </div>
                <div class="mb-3">
                    <label for="InputPhone" class="form-label">Phone</label>
                    <input type="text" id="InputPhone" class="form-control " placeholder="Votre numéro de telephone" name="tel">
                    @error('phone')
                    <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                </div>
                <div class="col-sm-6">
                    <button type="submit" class="btn btn-info">Valider</button>
                </div>

            </fieldset>
        </form>
       {{-- <a href="{{route('students.index')}}">Liste des étudiants</a>--}}
    </div>
</div>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
</body>
</html>

resources/views/students/edit.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
</head>
<body>

<div class="card col-sm-6 m-auto mt-5">
    <div class="card-body">
        <h1 class="justify-content-center">Modifier Etudiant</h1>

        <form method="POST" action="{{route('students.update',$student->id)}}">
            @csrf
            @method('PUT')
            <fieldset>
                <div class="mb-3">
                    <label for="Inputmatricule" class="form-label">Matricule</label>
                    <input type="text" id="Inputmatricule" class="form-control" value="{{$student->matricule}}" name="matricule">
                </div>
                <div class="mb-3">
                    <label for="InputFirstname" class="form-label">Prénom</label>
                    <input type="text" id="InputFirstname" class="form-control" value="{{$student->first_name}}" name="prenom">
                </div>
                <div class="mb-3">
                    <label for="InputLastname" class="form-label">Nom</label>
                    <input type="text" id="InputLastname" class="form-control" value="{{$student->last_name}}"  name="nom">
                </div>
                <div class="mb-3">
                    <label for="InputEmail" class="form-label">Email</label>
                    <input type="email" id="InputEmail" class="form-control" value="{{$student->email}}" name="email">
                </div>
                <div class="mb-3">
                    <label for="InputPhone" class="form-label">Phone</label>
                    <input type="text" id="InputPhone" class="form-control" value="{{$student->phone}}" name="tel">
                </div>
                <div class="col-sm-6">
                    <button type="submit" class="btn btn-info">Valider</button>
                </div>

            </fieldset>
        </form>
        {{--<a href="{{route('students.index')}}">Liste des étudiants</a>--}}
    </div>
</div>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
</body>
</html>

resources/views/students/index.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
</head>
<body>

<div class="card m-auto mt-5">
    <div class="card-body">
        <h1 class="justify-content-center">Liste de tous les étudiants</h1>
        <table class="table">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Matricule</th>
                <th scope="col">Prénom</th>
                <th scope="col">Nom</th>
                <th scope="col">Email</th>
                <th scope="col">Téléphone</th>
                <th scope="col">Action</th>
            </tr>
            </thead>
            <tbody>
            @foreach($students  as $student)
                <tr>
                    <td>{{$student->id}}</td>
                    <td>{{$student->matricule}}</td>
                    <td>{{$student->first_name}}</td>
                    <td>{{$student->last_name}}</td>
                    <td>{{$student->email}}</td>
                    <td>{{$student->phone}}</td>
                    <td>
                        <form action="{{ route('students.destroy',$student->id) }}" method="POST">

                            <a class="btn btn-info" href="{{ route('students.show',$student->id) }}">Show</a>

                            <a class="btn btn-primary" href="{{ route('students.edit',$student->id) }}">Edit</a>
                            @csrf
                            @method('DELETE')

                            <button type="submit" class="btn btn-danger">Delete</button>
                        </form>
                    </td>
                </tr>
            @endforeach

            </tbody>
        </table>
        <a href="{{route('students.create')}}">Nouveau etudiant</a>
    </div>
</div>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
</body>
</html>

resources/views/test.blade.php
<div>
    Hello World, today is {{$date}}
    Your name is , {{$name}}
</div>